// apps/web/src/features/report/pdf/pdfText.ts
//
// PDF raporunun statik, iki-dilli boilerplate metinleri. `types/enums.ts::
// LocalizedLabel` ({tr,en}) deseninin AYNISI — ama React'tan bağımsız (PDF
// üretimi component ağacının dışında çalışır, bkz. buildPdfDocDefinition.ts),
// bu yüzden `useTranslation()`/`translations.ts`'in kendisi DEĞİL, aynı
// deseni izleyen ayrı bir sözlük.
//
// KDP notu: bu dosyadaki metinler mühendislik SABİTİ/katsayı DEĞİLDİR
// (doküman şablonu/politika metni) — registry kaydı GEREKTİRMEZ. "İzleme
// önerileri" özellikle SAYISAL bir aralık İCAT ETMEZ (ör. "6 ayda bir UT
// taraması" gibi hafızadan bir sayı YAZILMAZ); yalnızca zaten hesaplanmış
// `CtlAtlCategory`ye bağlı NİTELİKSEL rehber metindir — nihai izleme sıklığı
// kararı kullanıcı tarafından yetkin bir korozyon mühendisine bırakılır
// (bkz. ENGINEERING_DISCLAIMER_TR ile aynı "belirsizlik dürüstlüğü" ilkesi).

import type { CtlAtlCategory } from "@erocorr3d/engine";
import type { ReportLanguage } from "../reportSettingsTypes";

export interface Bilingual {
  tr: string;
  en: string;
}

export function pick(text: Bilingual, lang: ReportLanguage): string {
  return lang === "tr" ? text.tr : text.en;
}

export const ENGINEERING_DISCLAIMER: Bilingual = {
  tr:
    "Bu sonuçlar mühendislik tahminidir. Model belirsizliği tipik olarak 2-3 kat mertebesindedir. " +
    "Nihai malzeme seçimi yetkin bir korozyon mühendisinin onayını gerektirir.",
  en:
    "These results are engineering estimates. Model uncertainty is typically on the order of 2-3x. " +
    "Final material selection requires the approval of a qualified corrosion engineer.",
};

export const SECTION_TITLES = {
  coverSubtitle: { tr: "Korozyon / Erozyon Değerlendirme Raporu", en: "Corrosion / Erosion Assessment Report" } as Bilingual,
  revisionHistory: { tr: "Revizyon Geçmişi", en: "Revision History" } as Bilingual,
  toc: { tr: "İçindekiler", en: "Table of Contents" } as Bilingual,
  introduction: { tr: "1. Giriş", en: "1. Introduction" } as Bilingual,
  scope: { tr: "2. Kapsam", en: "2. Scope" } as Bilingual,
  references: { tr: "3. Referanslar", en: "3. References" } as Bilingual,
  definitions: { tr: "4. Tanımlar ve Kısaltmalar", en: "4. Definitions and Abbreviations" } as Bilingual,
  designData: { tr: "5. Tasarım Verileri", en: "5. Design Data" } as Bilingual,
  mechanisms: { tr: "6. Değerlendirilen Mekanizmalar", en: "6. Mechanisms Evaluated" } as Bilingual,
  methodology: { tr: "7. Hesap Metodolojisi", en: "7. Calculation Methodology" } as Bilingual,
  results: { tr: "8. Sonuçlar", en: "8. Results" } as Bilingual,
  uncertainty: { tr: "9. Belirsizlik Analizi", en: "9. Uncertainty Analysis" } as Bilingual,
  materialSelection: { tr: "10. Malzeme Seçimi ve Gerekçesi", en: "10. Material Selection and Rationale" } as Bilingual,
  heatmap: { tr: "11. 3B Isı Haritası", en: "11. 3D Heatmap" } as Bilingual,
  charts: { tr: "12. Grafikler", en: "12. Charts" } as Bilingual,
  monitoring: { tr: "13. Korozyon İzleme Önerileri", en: "13. Corrosion Monitoring Recommendations" } as Bilingual,
  appendixA: { tr: "EK A: Ham Hesap Sonuçları", en: "APPENDIX A: Raw Calculation Results" } as Bilingual,
  appendixB: { tr: "EK B: Katsayı Kayıt Defteri", en: "APPENDIX B: Coefficient Registry" } as Bilingual,
};

export const INTRODUCTION_BODY: Bilingual = {
  tr:
    "Bu rapor, EroCorr3D yazılımı ile üretilmiştir. Aşağıda listelenen boru hattı/vana bileşenleri için " +
    "korozyon ve erozyon mekanizmaları, ilgili endüstri standartları ve hakemli literatüre dayalı modeller " +
    "kullanılarak değerlendirilmiştir. Rapor, mühendislik kararına yardımcı bir araçtır; nihai sorumluluk " +
    "yetkin mühendislik değerlendirmesindedir.",
  en:
    "This report was generated by the EroCorr3D software. The pipeline/valve components listed below have " +
    "been assessed for corrosion and erosion mechanisms using models based on relevant industry standards " +
    "and peer-reviewed literature. The report is an aid to engineering judgment; final responsibility rests " +
    "with qualified engineering review.",
};

export const SCOPE_BODY: Bilingual = {
  tr:
    "Bu değerlendirme, girilen geometri ve işletme senaryoları için iç yüzey korozyon/erozyon mekanizmalarını " +
    "kapsar. Yapısal bütünlük değerlendirmesi (ör. ASME B31G kalan dayanım analizi), kaynak/malzeme sertifikasyonu " +
    "ve saha muayene sonuçlarının değerlendirilmesi bu raporun kapsamı DIŞINDADIR.",
  en:
    "This assessment covers internal surface corrosion/erosion mechanisms for the entered geometry and operating " +
    "scenarios. Structural integrity assessment (e.g. ASME B31G remaining strength analysis), weld/material " +
    "certification, and evaluation of field inspection results are OUT OF SCOPE for this report.",
};

export const DEFINITIONS: { term: string; definitionTr: string; definitionEn: string }[] = [
  { term: "CTL", definitionTr: "Corroded Total Loss — tahmini toplam korozyon kaybı (mm)", definitionEn: "Corroded Total Loss — predicted total corrosion loss (mm)" },
  { term: "ATL", definitionTr: "Allowance Total Loss — seçilen korozyon payı (mm)", definitionEn: "Allowance Total Loss — selected corrosion allowance (mm)" },
  { term: "SLC", definitionTr: "Service Life Corrosion — tasarım ömrü sonundaki toplam metal kaybı", definitionEn: "Service Life Corrosion — total metal loss at end of design life" },
  { term: "P10/P50/P90", definitionTr: "İstatistiksel yüzdelikler — P50 merkezi tahmin, P90 koruyucu/yüksek tahmin", definitionEn: "Statistical percentiles — P50 central estimate, P90 conservative/high estimate" },
  { term: "KDP", definitionTr: "Kaynak Doğrulama Protokolü — her katsayının atıflı kaynağının kayıt altına alınması kuralı", definitionEn: "Source Verification Protocol — the rule that every coefficient must carry a cited source" },
];

const MONITORING_BY_CATEGORY: Record<CtlAtlCategory, Bilingual> = {
  NEGLIGIBLE: {
    tr: "CTL/ATL oranı ihmal edilebilir düzeyde — sistem tasarım ömründen daha uzun süre arızasız kalması beklenir. Standart periyodik gözle muayene programının sürdürülmesi yeterli olabilir; kesin izleme sıklığı yetkin bir korozyon mühendisi tarafından belirlenmelidir.",
    en: "The CTL/ATL ratio is negligible — the system is expected to remain intact well beyond its design life. Continuing a standard periodic visual inspection program may be sufficient; the exact monitoring frequency should be determined by a qualified corrosion engineer.",
  },
  LOW: {
    tr: "CTL/ATL oranı düşük — sistem tasarım ömrüne arızasız ulaşması beklenir. Yine de düzenli et kalınlığı muayenesi (UT/RT) ve korozyon kuponu/probu gibi izleme araçlarının değerlendirilmesi önerilir; program yetkin bir korozyon mühendisi tarafından tanımlanmalıdır.",
    en: "The CTL/ATL ratio is low — the system is expected to reach its design life without failure. Regular wall thickness inspection (UT/RT) and monitoring tools such as corrosion coupons/probes are nevertheless recommended for consideration; the program should be defined by a qualified corrosion engineer.",
  },
  MEDIUM: {
    tr: "CTL/ATL oranı orta — önlem alınmazsa sistem tasarım ömrünün %25'ine ulaştığında arızalanabilir. Artan sıklıkta et kalınlığı muayenesi, korozyon kuponu/probu ve/veya inhibitör izlemesi (varsa) yakından değerlendirilmelidir; izleme programı yetkin bir korozyon mühendisi tarafından tanımlanmalıdır.",
    en: "The CTL/ATL ratio is medium — without mitigation, the system may fail before reaching 25% of its design life. Increased-frequency wall thickness inspection, corrosion coupons/probes, and/or inhibitor monitoring (where applicable) should be closely evaluated; the monitoring program should be defined by a qualified corrosion engineer.",
  },
  HIGH: {
    tr: "CTL/ATL oranı yüksek — önlem alınmazsa sistem tasarım ömrünün %25'ine ulaşmadan ÖNCE arızalanacaktır. Sık aralıklı et kalınlığı muayenesi, sürekli izleme (probe/kupon) ve azaltma önlemlerinin (inhibitör, malzeme değişikliği) ACİLEN gözden geçirilmesi önerilir; izleme/azaltma programı yetkin bir korozyon mühendisi tarafından ivedilikle tanımlanmalıdır.",
    en: "The CTL/ATL ratio is high — without mitigation, the system will fail BEFORE reaching 25% of its design life. Frequent wall thickness inspection, continuous monitoring (probes/coupons), and an URGENT review of mitigation measures (inhibitor, material change) are recommended; the monitoring/mitigation program should be defined by a qualified corrosion engineer without delay.",
  },
};

export function monitoringRecommendationFor(category: CtlAtlCategory): Bilingual {
  return MONITORING_BY_CATEGORY[category];
}

export const MONITORING_NO_CTL_ATL: Bilingual = {
  tr: "Bu bileşen için korozyon payı girilmediğinden CTL/ATL oranı hesaplanamadı — bileşene özel bir izleme önerisi üretilemiyor. Korozyon payı girilerek değerlendirmenin tekrarlanması önerilir.",
  en: "The CTL/ATL ratio could not be computed for this component because no corrosion allowance was entered — a component-specific monitoring recommendation cannot be produced. Re-running the assessment with a corrosion allowance entered is recommended.",
};

export const HEATMAP_MISSING_NOTE: Bilingual = {
  tr: "Rapor üretilirken 3B görüntüleyici açık değildi — anlık görüntü alınamadı. Görüntüleyiciyi açıp raporu tekrar üretin.",
  en: "The 3D viewer was not open when the report was generated — a snapshot could not be captured. Open the viewer and regenerate the report.",
};

export const REFERENCES_LABEL: Bilingual = {
  tr: "Aşağıdaki kaynaklar, bu değerlendirmede kullanılan katsayıların atıflarıdır (bkz. EK B).",
  en: "The following are the citations for the coefficients used in this assessment (see Appendix B).",
};
